#!/bin/sh
####################
## Configuration file for varnish
##
##
## VARNISH_VCL_CONF=/etc/varnish/wpcloud-beta.vcl
##
####################

if [ -f /etc/environment ]; then
  . /etc/environment
fi;

VARNISH_INSTANCE_NAME=${VARNISH_INSTANCE_NAME:=$(hostname -s)}
VARNISH_VCL_CONF=${VARNISH_VCL_CONF:="/etc/varnish/mpo.vcl"}
VARNISH_LISTEN_ADDRESS=${VARNISH_LISTEN_ADDRESS:="0.0.0.0"}
VARNISH_LISTEN_PORT=${VARNISH_LISTEN_PORT:="6081"}
VARNISH_STORAGE_SIZE=${VARNISH_STORAGE_SIZE:="3G"}
VARNISH_SECRET_FILE=${VARNISH_SECRET_FILE:="/etc/varnish/secret.key"}
VARNISH_USER=${VARNISH_USER:="varnish"}
VARNISH_GROUP=${VARNISH_GROUP:="varnish"}
VARNISH_ADMIN_LISTEN_ADDRESS=${VARNISH_ADMIN_LISTEN_ADDRESS:="0.0.0.0"}
VARNISH_ADMIN_LISTEN_PORT=${VARNISH_ADMIN_LISTEN_PORT:="6082"}
VARNISH_STORAGE_PATH=/var/lib/varnish/${VARNISH_INSTANCE_NAME}
VARNISH_CLI_BUFFER=${VARNISH_CLI_BUFFER:="81920"}
VARNISH_DEFAULT_GRACE=200
VARNISH_DEFAULT_TTL=300
VARNISH_THREAD_POOLS=8
VARNISH_THREAD_DEPTH=512
VARNISH_THREAD_TIMEOUT=300
VARNISH_MIN_THREADS=300
VARNISH_MAX_THREADS=5000
VARNISH_TTL=120
VARNISH_STORAGE="malloc,${VARNISH_STORAGE_SIZE}"

if [ ! -e ${VARNISH_STORAGE_PATH} ]; then
  mkdir -p ${VARNISH_STORAGE_PATH}
fi

export DAEMON_OPTS=" \
  -a ${VARNISH_LISTEN_ADDRESS}:${VARNISH_LISTEN_PORT} \
  -s ${VARNISH_STORAGE} \
  -u ${VARNISH_USER} \
  -g ${VARNISH_GROUP} \
  -f ${VARNISH_VCL_CONF} \
  -T ${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT} \
  -t ${VARNISH_TTL} \
  -S ${VARNISH_SECRET_FILE} \
  -p http_gzip_support=true \
  -p thread_pool_max=${VARNISH_MAX_THREADS} \
  -p cli_buffer=${VARNISH_CLI_BUFFER} \
  -p default_grace=${VARNISH_DEFAULT_GRACE} \
  -p default_ttl=${VARNISH_DEFAULT_TTL} \
  -p thread_pool_min=${VARNISH_MIN_THREADS} \
  -p thread_pools=${VARNISH_THREAD_POOLS} \
  -p listen_depth=${VARNISH_THREAD_DEPTH}
  "

